#pragma once

#include <QDateTime>
#include <QHash>
#include <QMetaType>
#include <QString>
#include <QVector>
#include <optional>

enum class BridgeMaterialKind {
    Cookies,
    LocalStorage,
    Hybrid
};

struct BridgeClientId {
    QString browserFamily;      // chrome / edge / brave / opera / vivaldi
    QString profileInstanceId;  // stable UUID generated by extension per profile
    bool incognito = false;

    QString toBindingId() const {
        return browserFamily + QLatin1Char(':') + profileInstanceId;
    }

    bool operator==(const BridgeClientId& o) const {
        return browserFamily == o.browserFamily
            && profileInstanceId == o.profileInstanceId
            && incognito == o.incognito;
    }
};

inline size_t qHash(const BridgeClientId& id, size_t seed = 0) {
    return qHash(id.toBindingId(), seed);
}

struct BridgeClientInfo {
    BridgeClientId id;
    QString extensionId;
    QString extensionBuild;
    QString profileAlias;
    QString browserVersion;
    QDateTime connectedAt;
    QDateTime lastSeenAt;
    bool supportsCookies = true;
    bool supportsLocalStorage = false;
    bool supportsCodexUsageSnapshot = false;
    bool supportsCookieUrlQuery = false;
};

struct BridgeCookieRecord {
    QString name;
    QString value;
    QString domain;
    QString path;
    QString sameSite;
    QString storeId;
    bool secure = false;
    bool httpOnly = false;
    bool hostOnly = false;
    bool session = false;
    std::optional<QDateTime> expirationDateUtc;
    QString partitionKey;
};

struct BridgeSessionMaterial {
    QString providerId;
    BridgeClientId clientId;
    QVector<BridgeCookieRecord> cookies;
    QHash<QString, QString> localStorage;
    QDateTime capturedAtUtc;
    QString sourceReason;       // startup, manual_request, cookie_changed, page_probe
    int schemaVersion = 1;
};

struct BridgeSessionLookupInput {
    bool enabled = false;
    QString providerId;
    BridgeMaterialKind materialKind = BridgeMaterialKind::Cookies;
    QString cookieCredentialTarget;
    QString localStorageCredentialTarget;
};

struct BridgeBindingOption {
    QString bindingId;
    QString label;
    QString browserFamily;
    bool connected = false;
    bool hasMaterial = false;
};

Q_DECLARE_METATYPE(BridgeClientId)
Q_DECLARE_METATYPE(BridgeClientInfo)
Q_DECLARE_METATYPE(BridgeCookieRecord)
Q_DECLARE_METATYPE(BridgeSessionMaterial)
Q_DECLARE_METATYPE(BridgeSessionLookupInput)
Q_DECLARE_METATYPE(BridgeBindingOption)
